// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v4.24.4
// source: spire/server/kubernetestoken/v1/kubernetestoken.proto

package kubernetestokenv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignJWTRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// URL-safe base64 encoded JWT payload
	Payload       string `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignJWTRequest) Reset() {
	*x = SignJWTRequest{}
	mi := &file_spire_server_kubernetestoken_v1_kubernetestoken_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignJWTRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignJWTRequest) ProtoMessage() {}

func (x *SignJWTRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spire_server_kubernetestoken_v1_kubernetestoken_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignJWTRequest.ProtoReflect.Descriptor instead.
func (*SignJWTRequest) Descriptor() ([]byte, []int) {
	return file_spire_server_kubernetestoken_v1_kubernetestoken_proto_rawDescGZIP(), []int{0}
}

func (x *SignJWTRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type SignJWTResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// URL-safe base64 encoded JWT header
	Header string `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// URL-safe base64 encoded signature
	Signature     string `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignJWTResponse) Reset() {
	*x = SignJWTResponse{}
	mi := &file_spire_server_kubernetestoken_v1_kubernetestoken_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignJWTResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignJWTResponse) ProtoMessage() {}

func (x *SignJWTResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spire_server_kubernetestoken_v1_kubernetestoken_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignJWTResponse.ProtoReflect.Descriptor instead.
func (*SignJWTResponse) Descriptor() ([]byte, []int) {
	return file_spire_server_kubernetestoken_v1_kubernetestoken_proto_rawDescGZIP(), []int{1}
}

func (x *SignJWTResponse) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *SignJWTResponse) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type GetPublicKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicKeysRequest) Reset() {
	*x = GetPublicKeysRequest{}
	mi := &file_spire_server_kubernetestoken_v1_kubernetestoken_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicKeysRequest) ProtoMessage() {}

func (x *GetPublicKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spire_server_kubernetestoken_v1_kubernetestoken_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicKeysRequest.ProtoReflect.Descriptor instead.
func (*GetPublicKeysRequest) Descriptor() ([]byte, []int) {
	return file_spire_server_kubernetestoken_v1_kubernetestoken_proto_rawDescGZIP(), []int{2}
}

type GetPublicKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*PublicKey           `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicKeysResponse) Reset() {
	*x = GetPublicKeysResponse{}
	mi := &file_spire_server_kubernetestoken_v1_kubernetestoken_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicKeysResponse) ProtoMessage() {}

func (x *GetPublicKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spire_server_kubernetestoken_v1_kubernetestoken_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicKeysResponse.ProtoReflect.Descriptor instead.
func (*GetPublicKeysResponse) Descriptor() ([]byte, []int) {
	return file_spire_server_kubernetestoken_v1_kubernetestoken_proto_rawDescGZIP(), []int{3}
}

func (x *GetPublicKeysResponse) GetKeys() []*PublicKey {
	if x != nil {
		return x.Keys
	}
	return nil
}

type PublicKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicKey) Reset() {
	*x = PublicKey{}
	mi := &file_spire_server_kubernetestoken_v1_kubernetestoken_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKey) ProtoMessage() {}

func (x *PublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_spire_server_kubernetestoken_v1_kubernetestoken_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKey.ProtoReflect.Descriptor instead.
func (*PublicKey) Descriptor() ([]byte, []int) {
	return file_spire_server_kubernetestoken_v1_kubernetestoken_proto_rawDescGZIP(), []int{4}
}

func (x *PublicKey) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *PublicKey) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

var File_spire_server_kubernetestoken_v1_kubernetestoken_proto protoreflect.FileDescriptor

const file_spire_server_kubernetestoken_v1_kubernetestoken_proto_rawDesc = "" +
	"\n" +
	"5spire/server/kubernetestoken/v1/kubernetestoken.proto\x12\x1fspire.server.kubernetestoken.v1\"*\n" +
	"\x0eSignJWTRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\tR\apayload\"G\n" +
	"\x0fSignJWTResponse\x12\x16\n" +
	"\x06header\x18\x01 \x01(\tR\x06header\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\"\x16\n" +
	"\x14GetPublicKeysRequest\"W\n" +
	"\x15GetPublicKeysResponse\x12>\n" +
	"\x04keys\x18\x01 \x03(\v2*.spire.server.kubernetestoken.v1.PublicKeyR\x04keys\"4\n" +
	"\tPublicKey\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key2\xff\x01\n" +
	"\x0fKubernetesToken\x12l\n" +
	"\aSignJWT\x12/.spire.server.kubernetestoken.v1.SignJWTRequest\x1a0.spire.server.kubernetestoken.v1.SignJWTResponse\x12~\n" +
	"\rGetPublicKeys\x125.spire.server.kubernetestoken.v1.GetPublicKeysRequest\x1a6.spire.server.kubernetestoken.v1.GetPublicKeysResponseBQZOgithub.com/spiffe/spire/proto/spire/server/kubernetestoken/v1;kubernetestokenv1b\x06proto3"

var (
	file_spire_server_kubernetestoken_v1_kubernetestoken_proto_rawDescOnce sync.Once
	file_spire_server_kubernetestoken_v1_kubernetestoken_proto_rawDescData []byte
)

func file_spire_server_kubernetestoken_v1_kubernetestoken_proto_rawDescGZIP() []byte {
	file_spire_server_kubernetestoken_v1_kubernetestoken_proto_rawDescOnce.Do(func() {
		file_spire_server_kubernetestoken_v1_kubernetestoken_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spire_server_kubernetestoken_v1_kubernetestoken_proto_rawDesc), len(file_spire_server_kubernetestoken_v1_kubernetestoken_proto_rawDesc)))
	})
	return file_spire_server_kubernetestoken_v1_kubernetestoken_proto_rawDescData
}

var file_spire_server_kubernetestoken_v1_kubernetestoken_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_spire_server_kubernetestoken_v1_kubernetestoken_proto_goTypes = []any{
	(*SignJWTRequest)(nil),        // 0: spire.server.kubernetestoken.v1.SignJWTRequest
	(*SignJWTResponse)(nil),       // 1: spire.server.kubernetestoken.v1.SignJWTResponse
	(*GetPublicKeysRequest)(nil),  // 2: spire.server.kubernetestoken.v1.GetPublicKeysRequest
	(*GetPublicKeysResponse)(nil), // 3: spire.server.kubernetestoken.v1.GetPublicKeysResponse
	(*PublicKey)(nil),             // 4: spire.server.kubernetestoken.v1.PublicKey
}
var file_spire_server_kubernetestoken_v1_kubernetestoken_proto_depIdxs = []int32{
	4, // 0: spire.server.kubernetestoken.v1.GetPublicKeysResponse.keys:type_name -> spire.server.kubernetestoken.v1.PublicKey
	0, // 1: spire.server.kubernetestoken.v1.KubernetesToken.SignJWT:input_type -> spire.server.kubernetestoken.v1.SignJWTRequest
	2, // 2: spire.server.kubernetestoken.v1.KubernetesToken.GetPublicKeys:input_type -> spire.server.kubernetestoken.v1.GetPublicKeysRequest
	1, // 3: spire.server.kubernetestoken.v1.KubernetesToken.SignJWT:output_type -> spire.server.kubernetestoken.v1.SignJWTResponse
	3, // 4: spire.server.kubernetestoken.v1.KubernetesToken.GetPublicKeys:output_type -> spire.server.kubernetestoken.v1.GetPublicKeysResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_spire_server_kubernetestoken_v1_kubernetestoken_proto_init() }
func file_spire_server_kubernetestoken_v1_kubernetestoken_proto_init() {
	if File_spire_server_kubernetestoken_v1_kubernetestoken_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spire_server_kubernetestoken_v1_kubernetestoken_proto_rawDesc), len(file_spire_server_kubernetestoken_v1_kubernetestoken_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spire_server_kubernetestoken_v1_kubernetestoken_proto_goTypes,
		DependencyIndexes: file_spire_server_kubernetestoken_v1_kubernetestoken_proto_depIdxs,
		MessageInfos:      file_spire_server_kubernetestoken_v1_kubernetestoken_proto_msgTypes,
	}.Build()
	File_spire_server_kubernetestoken_v1_kubernetestoken_proto = out.File
	file_spire_server_kubernetestoken_v1_kubernetestoken_proto_goTypes = nil
	file_spire_server_kubernetestoken_v1_kubernetestoken_proto_depIdxs = nil
}
