// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.24.4
// source: spire/server/kubernetestoken/v1/kubernetestoken.proto

package kubernetestokenv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KubernetesToken_SignJWT_FullMethodName       = "/spire.server.kubernetestoken.v1.KubernetesToken/SignJWT"
	KubernetesToken_GetPublicKeys_FullMethodName = "/spire.server.kubernetestoken.v1.KubernetesToken/GetPublicKeys"
)

// KubernetesTokenClient is the client API for KubernetesToken service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KubernetesTokenClient interface {
	SignJWT(ctx context.Context, in *SignJWTRequest, opts ...grpc.CallOption) (*SignJWTResponse, error)
	GetPublicKeys(ctx context.Context, in *GetPublicKeysRequest, opts ...grpc.CallOption) (*GetPublicKeysResponse, error)
}

type kubernetesTokenClient struct {
	cc grpc.ClientConnInterface
}

func NewKubernetesTokenClient(cc grpc.ClientConnInterface) KubernetesTokenClient {
	return &kubernetesTokenClient{cc}
}

func (c *kubernetesTokenClient) SignJWT(ctx context.Context, in *SignJWTRequest, opts ...grpc.CallOption) (*SignJWTResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignJWTResponse)
	err := c.cc.Invoke(ctx, KubernetesToken_SignJWT_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubernetesTokenClient) GetPublicKeys(ctx context.Context, in *GetPublicKeysRequest, opts ...grpc.CallOption) (*GetPublicKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPublicKeysResponse)
	err := c.cc.Invoke(ctx, KubernetesToken_GetPublicKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KubernetesTokenServer is the server API for KubernetesToken service.
// All implementations must embed UnimplementedKubernetesTokenServer
// for forward compatibility.
type KubernetesTokenServer interface {
	SignJWT(context.Context, *SignJWTRequest) (*SignJWTResponse, error)
	GetPublicKeys(context.Context, *GetPublicKeysRequest) (*GetPublicKeysResponse, error)
	mustEmbedUnimplementedKubernetesTokenServer()
}

// UnimplementedKubernetesTokenServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKubernetesTokenServer struct{}

func (UnimplementedKubernetesTokenServer) SignJWT(context.Context, *SignJWTRequest) (*SignJWTResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignJWT not implemented")
}
func (UnimplementedKubernetesTokenServer) GetPublicKeys(context.Context, *GetPublicKeysRequest) (*GetPublicKeysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPublicKeys not implemented")
}
func (UnimplementedKubernetesTokenServer) mustEmbedUnimplementedKubernetesTokenServer() {}
func (UnimplementedKubernetesTokenServer) testEmbeddedByValue()                         {}

// UnsafeKubernetesTokenServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KubernetesTokenServer will
// result in compilation errors.
type UnsafeKubernetesTokenServer interface {
	mustEmbedUnimplementedKubernetesTokenServer()
}

func RegisterKubernetesTokenServer(s grpc.ServiceRegistrar, srv KubernetesTokenServer) {
	// If the following call pancis, it indicates UnimplementedKubernetesTokenServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KubernetesToken_ServiceDesc, srv)
}

func _KubernetesToken_SignJWT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignJWTRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubernetesTokenServer).SignJWT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KubernetesToken_SignJWT_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubernetesTokenServer).SignJWT(ctx, req.(*SignJWTRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KubernetesToken_GetPublicKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublicKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubernetesTokenServer).GetPublicKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KubernetesToken_GetPublicKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubernetesTokenServer).GetPublicKeys(ctx, req.(*GetPublicKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KubernetesToken_ServiceDesc is the grpc.ServiceDesc for KubernetesToken service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KubernetesToken_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "spire.server.kubernetestoken.v1.KubernetesToken",
	HandlerType: (*KubernetesTokenServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignJWT",
			Handler:    _KubernetesToken_SignJWT_Handler,
		},
		{
			MethodName: "GetPublicKeys",
			Handler:    _KubernetesToken_GetPublicKeys_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "spire/server/kubernetestoken/v1/kubernetestoken.proto",
}
